import Head from "next/head";

export const metadata = {
  title: "AutoMode",
  description: "Generated by create next app",
  viewport:
    "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0",
};

export default function CustomHead() {
  return (
    <Head>
      <title>{metadata.title}</title>
      <meta name="description" content={metadata.description} />
      <meta name="viewport" content={metadata.viewport} />
    </Head>
  );
}
