const dataGrid = [
  {
    key: "1",
    org_cat: "IT Company",
    status: "Active",
    icon: "https://via.placeholder.com/150",
    orgName: "AutomodeAI",
    userRole: "Inventory Manager",
    primaryContact: "Parth Goswami",
    subscription: {
      plan: "Basic",
      expiresOn: "20 Aug 2023",
      daysLeft: 0,
    },
  },
  {
    key: "2",
    org_cat: "Hotel",
    status: "Inactive",
    icon: "https://via.placeholder.com/150",
    orgName: "AutomodeAI",
    userRole: "Inventory Manager",
    primaryContact: "Parth Goswami",
    subscription: {
      plan: "Premium",
      expiresOn: "20 Aug 2023",
      daysLeft: -20,
    },
  },
  {
    key: "3",
    org_cat: "Textile",
    status: "Inactive",
    icon: "https://via.placeholder.com/150",
    orgName: "AutomodeAI",
    userRole: "Inventory Manager",
    primaryContact: "Parth Goswami",
    subscription: {
      plan: "Basic",
      expiresOn: "20 Aug 2023",
      daysLeft: -1,
    },
  },
  {
    key: "4",
    org_cat: "IT Company",
    status: "Active",
    icon: "https://via.placeholder.com/150",
    orgName: "AutomodeAI",
    userRole: "Inventory Manager",
    primaryContact: "Parth Goswami",
    subscription: {
      plan: "Premium",
      expiresOn: "20 Aug 2023",
      daysLeft: 1,
    },
  },
  {
    key: "5",
    org_cat: "IT Company",
    status: "Active",
    icon: "https://via.placeholder.com/150",
    orgName: "AutomodeAI",
    userRole: "Inventory Manager",
    primaryContact: "Parth Goswami",
    subscription: {
      plan: "Premium",
      expiresOn: "20 Aug 2023",
      daysLeft: 1,
    },
  },
  {
    key: "6",
    org_cat: "IT Company",
    status: "Active",
    icon: "https://via.placeholder.com/150",
    orgName: "AutomodeAI",
    userRole: "Inventory Manager",
    primaryContact: "Parth Goswami",
    subscription: {
      plan: "Premium",
      expiresOn: "20 Aug 2023",
      daysLeft: 1,
    },
  },
];

export default dataGrid;
